### ISSUE TITLE
test failure: Expected values to be near

### ISSUE THREAD

**Issue by jpleau** [o-lim/luasystem#1]
Hi.

I'm currently packaging luasystem for Debian (as a dependency of busted)

I ran into a test failure:

```
1 success / 1 failure / 0 errors / 0 pending : 0.500998 seconds

Failure → spec/time_spec.lua @ 4
Test time functions gettime returns current time
spec/time_spec.lua:5: Expected values to be near.
Passed in:
(number) 1456083442.0007779598
Expected:
(number) 1456083441 +/- 1
```
This was with Lua5.1 (could not reproduce with 5.2 or 5.3, maybe it was just bad luck!)

Running the tests again work fine. Looks like the two calls to os.time() and system.gettime() were too far from each other.

Would the solution be to increase the limit? This is very arbitrary as on some systems it could take longer to call both functions.

**Comment by o-lim** [comment]
This test is not very robust since it depends on the time for the system to execute the test, but I couldn't come up with any thing better.  And the test is really a sanity check anyways.  I had thought that 1 second would be plenty of time, which still seems to be the case, since your test only too 0.5 seconds.  The failure is probably due to `os.time` truncating the time, so making the tolerance more like 2 should fix it for this scenario.

When you package for Debian, are you running the test as part of the installation? Or are you just running it manually. To make sure it works on our system?

**Comment by jpleau** [comment]
Hi

The tests are run as part of the normal package building process. They'll also be ran on Debian servers when packages are built, and to test if packages are reproducible.

Adjusting the limit to two seconds sounds reasonable, I still can't reproduce the bug so it's very likely I was unlucky. 

Thanks !

**Comment by o-lim** [comment]
I updated the test to be more robust. You can try out the latest master branch.

**Comment by jpleau** [comment]
I can't reproduce anymore (nor get unlucky ;) )

Thanks!
